import WallpaperGroups.Invariants.DihedralShift
import WallpaperGroups.Presentations.DihedralExtension
import WallpaperGroups.Restriction.DihedralNormalForms
import Mathlib.GroupTheory.SpecificGroups.Dihedral

set_option linter.style.header false

/-!
# Extensions generated by two adjacent reflections

This file refines `DihedralExtensionData` for the presentation used by the multiple-reflection
classification.  Given adjacent point reflections `s` and `t`, choose affine lifts `S` and `T`
and put `R = S * T`.  The rotation lift has the exact finite period of the point rotation.  We use
the canonical dihedral words

```text
r i  |-> R^i,        sr i |-> S * R^i.
```

The multiplication table of these words is controlled by the lattice action and the two square
translations `S^2` and `T^2`.  The exact comparison theorem below packages this observation as a
translation-preserving isomorphism.  Its quotient-valued version first adjusts the two target
lifts by norm vectors and then applies the exact theorem.
-/

set_option autoImplicit false

namespace WallpaperGroups

open EuclideanMotion

noncomputable section

/-- Affine lifts of the two adjacent point reflections selected by `DihedralGenerators`. -/
structure TwoReflectionExtensionData (G : PlaneGroup) (d : DihedralGenerators G) where
  /-- Lift of the first reflection. -/
  firstLift : G.carrier
  /-- The first lift has the selected first reflection as linear part. -/
  first_projection : pointProjection G.carrier firstLift = d.reflection
  /-- Lift of the adjacent second reflection. -/
  secondLift : G.carrier
  /-- The second lift has the selected adjacent reflection as linear part. -/
  second_projection : pointProjection G.carrier secondLift = d.secondReflection

namespace TwoReflectionExtensionData

variable {G : PlaneGroup} {d : DihedralGenerators G}

/-- Choose the two generator lifts from surjectivity of the point projection. -/
noncomputable def choose (G : PlaneGroup) (d : DihedralGenerators G) :
    TwoReflectionExtensionData G d where
  firstLift := Classical.choose (pointProjection_surjective G.carrier d.reflection)
  first_projection := Classical.choose_spec
    (pointProjection_surjective G.carrier d.reflection)
  secondLift := Classical.choose (pointProjection_surjective G.carrier d.secondReflection)
  second_projection := Classical.choose_spec
    (pointProjection_surjective G.carrier d.secondReflection)

/-- The affine rotation lift is the product of the adjacent reflection lifts. -/
def rotationLift (c : TwoReflectionExtensionData G d) : G.carrier :=
  c.firstLift * c.secondLift

/-- The product lift projects to the selected positive point generator. -/
@[simp]
theorem rotationLift_projection (c : TwoReflectionExtensionData G d) :
    pointProjection G.carrier c.rotationLift = d.rotation.1 := by
  rw [rotationLift, map_mul, c.first_projection, c.second_projection,
    d.reflection_mul_secondReflection]

/-- The rotation lift has the advertised finite period. -/
theorem rotationLift_pow_order (c : TwoReflectionExtensionData G d) :
    c.rotationLift ^ d.order.toNat = 1 := by
  apply Subtype.ext
  change (c.rotationLift : EuclideanMotion Plane) ^ d.order.toNat = 1
  apply orientationPreserving_lift_pow_eq_one G d.rotation d.rotation_ne_one
      c.rotationLift c.rotationLift_projection d.order.toNat
  rw [← d.rotation_order]
  exact pow_orderOf_eq_one d.rotation.1

/-- Powers of the rotation lift, indexed without a choice of integer representative. -/
def rotationLiftHom (c : TwoReflectionExtensionData G d) :
    Multiplicative (ZMod d.order.toNat) →* G.carrier :=
  zmodPowerHom d.order.toNat c.rotationLift c.rotationLift_pow_order

/-- Powers of the selected point rotation. -/
def pointRotationHom (d : DihedralGenerators G) :
    Multiplicative (ZMod d.order.toNat) →* pointGroup G.carrier :=
  zmodPowerHom d.order.toNat d.rotation.1 (by
    rw [← d.rotation_order]
    exact pow_orderOf_eq_one d.rotation.1)

/-- Projection commutes with the finite cyclic rotation coordinates. -/
@[simp]
theorem rotationLiftHom_projection (c : TwoReflectionExtensionData G d)
    (i : Multiplicative (ZMod d.order.toNat)) :
    pointProjection G.carrier (c.rotationLiftHom i) = pointRotationHom d i := by
  let hG : G.carrier →* pointGroup G.carrier := pointProjection G.carrier
  have hcomp : hG.comp c.rotationLiftHom = pointRotationHom d := by
    apply MonoidHom.ext
    intro i
    obtain ⟨z, rfl⟩ : ∃ z : ℤ,
        i = Multiplicative.ofAdd (z : ZMod d.order.toNat) :=
      ⟨ZMod.cast i.toAdd, by
        apply Multiplicative.toAdd.injective
        exact (ZMod.intCast_zmod_cast i.toAdd).symm⟩
    simp [rotationLiftHom, pointRotationHom, hG, c.rotationLift_projection]
  exact DFunLike.congr_fun hcomp i

/-- The exact square translation of the first reflection lift. -/
def firstSquareShift (c : TwoReflectionExtensionData G d) :
    translationVectors G.carrier :=
  liftPowerTranslation G d.reflection 2 d.reflection_sq
    c.firstLift c.first_projection

/-- The exact square translation of the adjacent second reflection lift. -/
def secondSquareShift (c : TwoReflectionExtensionData G d) :
    translationVectors G.carrier :=
  liftPowerTranslation G d.secondReflection 2 d.secondReflection_sq
    c.secondLift c.second_projection

/-- The first lift squares to its stored exact shift. -/
theorem firstLift_sq (c : TwoReflectionExtensionData G d) :
    c.firstLift ^ 2 = translationElement G.carrier c.firstSquareShift := by
  apply Subtype.ext
  change (c.firstLift : EuclideanMotion Plane) ^ 2 =
    translation (c.firstSquareShift : Plane)
  have hlinear : linearPart ((c.firstLift : EuclideanMotion Plane) ^ 2) = 1 := by
    rw [map_pow]
    have hfirst : linearPart (c.firstLift : EuclideanMotion Plane) =
        (d.reflection : Plane ≃ₗᵢ[ℝ] Plane) := by
      simpa only [pointProjection_coe] using congrArg Subtype.val c.first_projection
    rw [hfirst]
    exact congrArg Subtype.val d.reflection_sq
  rw [eq_translation_of_linearPart_eq_one hlinear]
  rfl

/-- The second lift squares to its stored exact shift. -/
theorem secondLift_sq (c : TwoReflectionExtensionData G d) :
    c.secondLift ^ 2 = translationElement G.carrier c.secondSquareShift := by
  apply Subtype.ext
  change (c.secondLift : EuclideanMotion Plane) ^ 2 =
    translation (c.secondSquareShift : Plane)
  have hlinear : linearPart ((c.secondLift : EuclideanMotion Plane) ^ 2) = 1 := by
    rw [map_pow]
    have hsecond : linearPart (c.secondLift : EuclideanMotion Plane) =
        (d.secondReflection : Plane ≃ₗᵢ[ℝ] Plane) := by
      simpa only [pointProjection_coe] using congrArg Subtype.val c.second_projection
    rw [hsecond]
    exact congrArg Subtype.val d.secondReflection_sq
  rw [eq_translation_of_linearPart_eq_one hlinear]
  rfl

/-- The first square shift as a quotient-valued reflection shift. -/
def firstShiftClass (c : TwoReflectionExtensionData G d) :
    ShiftClassGroup G d.reflection 2 d.reflection_sq :=
  shiftClass G d.reflection 2 d.reflection_sq c.firstLift c.first_projection

/-- The second square shift as a quotient-valued reflection shift. -/
def secondShiftClass (c : TwoReflectionExtensionData G d) :
    ShiftClassGroup G d.secondReflection 2 d.secondReflection_sq :=
  shiftClass G d.secondReflection 2 d.secondReflection_sq
    c.secondLift c.second_projection

/-- Vanishing of a shift class is insensitive to propositionally equal presentations of its
point element and the proof parameters depending on that element. -/
private theorem shiftClass_eq_zero_congr_point_aux
    {G : PlaneGroup} {h k : pointGroup G.carrier} (hhk : h = k)
    (q : ℕ) (hq : h ^ q = 1) (kq : k ^ q = 1)
    (g : G.carrier) (hg : pointProjection G.carrier g = h)
    (kg : pointProjection G.carrier g = k) :
    shiftClass G h q hq g hg = 0 ↔ shiftClass G k q kq g kg = 0 := by
  subst k
  rfl

/-! ## The order-two generator-swap symmetry -/

/-- Rotating the selected reflection generator once makes the old adjacent reflection the new
first reflection. -/
@[simp]
theorem rotateReflection_one_reflection_eq_secondReflection
    (d : DihedralGenerators G) :
    (d.rotateReflection 1).reflection = d.secondReflection := by
  simp [DihedralGenerators.secondReflection]

/-- In rotation order two, rotating the reflection generator once makes the old first
reflection the new adjacent reflection. -/
theorem rotateReflection_one_secondReflection_eq_reflection
    (d : DihedralGenerators G) (horder : d.order = .two) :
    (d.rotateReflection 1).secondReflection = d.reflection := by
  have hrotation_sq : d.rotation.1 ^ 2 = 1 := by
    have h := pow_orderOf_eq_one d.rotation.1
    rw [d.rotation_order, horder] at h
    simpa [DihedralRotationOrder.toNat] using h
  rw [DihedralGenerators.secondReflection,
    DihedralGenerators.rotateReflection_reflection,
    DihedralGenerators.rotateReflection_rotation]
  simp only [pow_one]
  calc
    (d.reflection * d.rotation.1) * d.rotation.1 =
        d.reflection * (d.rotation.1 ^ 2) := by rw [pow_two, mul_assoc]
    _ = d.reflection := by rw [hrotation_sq, mul_one]

/-- For rotation order two, swap the two adjacent affine reflection lifts by rotating the
chosen point-reflection generator once. -/
def swapOrderTwo (c : TwoReflectionExtensionData G d) (horder : d.order = .two) :
    TwoReflectionExtensionData G (d.rotateReflection 1) where
  firstLift := c.secondLift
  first_projection := c.second_projection.trans
    (rotateReflection_one_reflection_eq_secondReflection d).symm
  secondLift := c.firstLift
  second_projection := c.first_projection.trans
    (rotateReflection_one_secondReflection_eq_reflection d horder).symm

/-- The first shift class of the swapped order-two presentation vanishes exactly when the old
second shift class vanishes. -/
theorem swapOrderTwo_firstShiftClass_eq_zero_iff
    (c : TwoReflectionExtensionData G d) (horder : d.order = .two) :
    (c.swapOrderTwo horder).firstShiftClass = 0 ↔ c.secondShiftClass = 0 := by
  change
    shiftClass G (d.rotateReflection 1).reflection 2
        (d.rotateReflection 1).reflection_sq c.secondLift _ = 0 ↔
      shiftClass G d.secondReflection 2 d.secondReflection_sq
        c.secondLift c.second_projection = 0
  exact shiftClass_eq_zero_congr_point_aux
    (rotateReflection_one_reflection_eq_secondReflection d) 2
    (d.rotateReflection 1).reflection_sq d.secondReflection_sq
    c.secondLift _ c.second_projection

/-- The second shift class of the swapped order-two presentation vanishes exactly when the old
first shift class vanishes. -/
theorem swapOrderTwo_secondShiftClass_eq_zero_iff
    (c : TwoReflectionExtensionData G d) (horder : d.order = .two) :
    (c.swapOrderTwo horder).secondShiftClass = 0 ↔ c.firstShiftClass = 0 := by
  change
    shiftClass G (d.rotateReflection 1).secondReflection 2
        (d.rotateReflection 1).secondReflection_sq c.firstLift _ = 0 ↔
      shiftClass G d.reflection 2 d.reflection_sq
        c.firstLift c.first_projection = 0
  exact shiftClass_eq_zero_congr_point_aux
    (rotateReflection_one_secondReflection_eq_reflection d horder) 2
    (d.rotateReflection 1).secondReflection_sq d.reflection_sq
    c.firstLift _ c.first_projection

/-! ## Canonical dihedral coordinates and section -/

/-- The finite cyclic point-rotation coordinate is faithful because the generator has exact
order `d.order.toNat`. -/
theorem pointRotationHom_injective (d : DihedralGenerators G) :
    Function.Injective (pointRotationHom d) := by
  intro i j hij
  obtain ⟨a, rfl⟩ : ∃ a : ℤ,
      i = Multiplicative.ofAdd (a : ZMod d.order.toNat) :=
    ⟨ZMod.cast i.toAdd, by
      apply Multiplicative.toAdd.injective
      exact (ZMod.intCast_zmod_cast i.toAdd).symm⟩
  obtain ⟨b, rfl⟩ : ∃ b : ℤ,
      j = Multiplicative.ofAdd (b : ZMod d.order.toNat) :=
    ⟨ZMod.cast j.toAdd, by
      apply Multiplicative.toAdd.injective
      exact (ZMod.intCast_zmod_cast j.toAdd).symm⟩
  simp only [pointRotationHom, zmodPowerHom_ofAdd_intCast] at hij
  apply Multiplicative.toAdd.injective
  change (a : ZMod d.order.toNat) = (b : ZMod d.order.toNat)
  rw [ZMod.intCast_eq_intCast_iff]
  rw [← d.rotation_order]
  exact zpow_eq_zpow_iff_modEq.mp hij

/-- Every finite cyclic point-rotation coordinate remains orientation preserving. -/
theorem pointRotationHom_mem_orientationPreserving (d : DihedralGenerators G)
    (i : Multiplicative (ZMod d.order.toNat)) :
    pointRotationHom d i ∈ orientationPreservingPointGroup G := by
  obtain ⟨a, rfl⟩ : ∃ a : ℤ,
      i = Multiplicative.ofAdd (a : ZMod d.order.toNat) :=
    ⟨ZMod.cast i.toAdd, by
      apply Multiplicative.toAdd.injective
      exact (ZMod.intCast_zmod_cast i.toAdd).symm⟩
  rw [pointRotationHom, zmodPowerHom_ofAdd_intCast]
  exact (d.rotation ^ a).property

/-- The first point reflection commutes past a cyclic rotation coordinate by inversion. -/
theorem reflection_mul_pointRotationHom (d : DihedralGenerators G)
    (i : Multiplicative (ZMod d.order.toNat)) :
    d.reflection * pointRotationHom d i =
      pointRotationHom d i⁻¹ * d.reflection := by
  let r : orientationPreservingPointGroup G :=
    ⟨pointRotationHom d i, pointRotationHom_mem_orientationPreserving d i⟩
  have hconj := pointGroup_reversing_conjugates_to_inverse G d.reflection
    d.reflection_reversing r
  calc
    d.reflection * pointRotationHom d i =
        (d.reflection * pointRotationHom d i * d.reflection⁻¹) * d.reflection := by
      group
    _ = (pointRotationHom d i)⁻¹ * d.reflection := by rw [hconj]
    _ = pointRotationHom d i⁻¹ * d.reflection := by rw [map_inv]

/-- The equivalent commutation rule with the rotation on the left. -/
theorem pointRotationHom_mul_reflection (d : DihedralGenerators G)
    (i : Multiplicative (ZMod d.order.toNat)) :
    pointRotationHom d i * d.reflection =
      d.reflection * pointRotationHom d i⁻¹ := by
  simpa using (reflection_mul_pointRotationHom d i⁻¹).symm

/-- Interpret the abstract dihedral group in the selected point group. -/
def pointDihedralHom (d : DihedralGenerators G) :
    DihedralGroup d.order.toNat →* pointGroup G.carrier where
  toFun
    | .r i => pointRotationHom d (Multiplicative.ofAdd i)
    | .sr i => d.reflection * pointRotationHom d (Multiplicative.ofAdd i)
  map_one' := by
    change pointRotationHom d (Multiplicative.ofAdd 0) = 1
    exact map_one (pointRotationHom d)
  map_mul' x y := by
    cases x with
    | r i =>
        cases y with
        | r j => simp
        | sr j =>
            rw [DihedralGroup.r_mul_sr]
            change d.reflection * pointRotationHom d (Multiplicative.ofAdd (j - i)) =
              pointRotationHom d (Multiplicative.ofAdd i) *
                (d.reflection * pointRotationHom d (Multiplicative.ofAdd j))
            calc
              d.reflection * pointRotationHom d (Multiplicative.ofAdd (j - i)) =
                  d.reflection *
                    (pointRotationHom d (Multiplicative.ofAdd i)⁻¹ *
                      pointRotationHom d (Multiplicative.ofAdd j)) := by
                congr 1
                rw [← map_mul]
                congr 1
                apply Multiplicative.toAdd.injective
                change j - i = -i + j
                abel
              _ = (d.reflection *
                    pointRotationHom d (Multiplicative.ofAdd i)⁻¹) *
                      pointRotationHom d (Multiplicative.ofAdd j) := by group
              _ = (pointRotationHom d (Multiplicative.ofAdd i) * d.reflection) *
                      pointRotationHom d (Multiplicative.ofAdd j) := by
                rw [pointRotationHom_mul_reflection]
              _ = pointRotationHom d (Multiplicative.ofAdd i) *
                    (d.reflection * pointRotationHom d (Multiplicative.ofAdd j)) := by
                group
    | sr i =>
        cases y with
        | r j =>
            change d.reflection * pointRotationHom d (Multiplicative.ofAdd (i + j)) =
              (d.reflection * pointRotationHom d (Multiplicative.ofAdd i)) *
                pointRotationHom d (Multiplicative.ofAdd j)
            rw [mul_assoc, ← map_mul]
            rfl
        | sr j =>
            rw [DihedralGroup.sr_mul_sr]
            change pointRotationHom d (Multiplicative.ofAdd (j - i)) =
              (d.reflection * pointRotationHom d (Multiplicative.ofAdd i)) *
                (d.reflection * pointRotationHom d (Multiplicative.ofAdd j))
            symm
            calc
              (d.reflection * pointRotationHom d (Multiplicative.ofAdd i)) *
                    (d.reflection * pointRotationHom d (Multiplicative.ofAdd j)) =
                  d.reflection *
                    (pointRotationHom d (Multiplicative.ofAdd i) * d.reflection) *
                      pointRotationHom d (Multiplicative.ofAdd j) := by group
              _ = d.reflection *
                    (d.reflection * pointRotationHom d (Multiplicative.ofAdd i)⁻¹) *
                      pointRotationHom d (Multiplicative.ofAdd j) := by
                rw [pointRotationHom_mul_reflection]
              _ = pointRotationHom d (Multiplicative.ofAdd i)⁻¹ *
                    pointRotationHom d (Multiplicative.ofAdd j) := by
                rw [← mul_assoc]
                rw [show d.reflection * d.reflection = 1 by
                  simpa [pow_two] using d.reflection_sq]
                simp
              _ = pointRotationHom d (Multiplicative.ofAdd (j - i)) := by
                rw [← map_mul]
                congr 1
                apply Multiplicative.toAdd.injective
                change -i + j = j - i
                abel

/-- Evaluation of the canonical point homomorphism on a rotation coordinate. -/
@[simp]
theorem pointDihedralHom_r (d : DihedralGenerators G)
    (i : ZMod d.order.toNat) :
    pointDihedralHom d (.r i) = pointRotationHom d (Multiplicative.ofAdd i) :=
  rfl

/-- Evaluation of the canonical point homomorphism on a reflection coordinate. -/
@[simp]
theorem pointDihedralHom_sr (d : DihedralGenerators G)
    (i : ZMod d.order.toNat) :
    pointDihedralHom d (.sr i) =
      d.reflection * pointRotationHom d (Multiplicative.ofAdd i) :=
  rfl

/-- The abstract dihedral coordinates exhaust the selected point group. -/
theorem pointDihedralHom_surjective (d : DihedralGenerators G) :
    Function.Surjective (pointDihedralHom d) := by
  intro q
  rcases d.point_two_coset_normal_form q with
    ⟨r, ⟨a, ha⟩, rfl⟩ | ⟨r, ⟨a, ha⟩, rfl⟩
  · refine ⟨DihedralGroup.r (a : ZMod d.order.toNat), ?_⟩
    change pointRotationHom d (Multiplicative.ofAdd (a : ZMod d.order.toNat)) = r.1
    unfold pointRotationHom
    rw [zmodPowerHom_ofAdd_intCast]
    exact congrArg Subtype.val ha
  · refine ⟨DihedralGroup.sr (a : ZMod d.order.toNat), ?_⟩
    change d.reflection *
      pointRotationHom d (Multiplicative.ofAdd (a : ZMod d.order.toNat)) =
        d.reflection * r.1
    unfold pointRotationHom
    rw [zmodPowerHom_ofAdd_intCast]
    exact congrArg (d.reflection * ·) (congrArg Subtype.val ha)

/-- The abstract dihedral coordinates are unique. -/
theorem pointDihedralHom_injective (d : DihedralGenerators G) :
    Function.Injective (pointDihedralHom d) := by
  intro x y hxy
  cases x with
  | r i =>
      cases y with
      | r j =>
          congr 1
          apply Multiplicative.ofAdd.injective
          exact pointRotationHom_injective d hxy
      | sr j =>
          exfalso
          apply d.reflection_reversing
          have hi := pointRotationHom_mem_orientationPreserving d
            (Multiplicative.ofAdd i)
          have hj := pointRotationHom_mem_orientationPreserving d
            (Multiplicative.ofAdd j)
          have hprod := (orientationPreservingPointGroup G).mul_mem hi
            ((orientationPreservingPointGroup G).inv_mem hj)
          change pointRotationHom d (Multiplicative.ofAdd i) =
            d.reflection * pointRotationHom d (Multiplicative.ofAdd j) at hxy
          have href : d.reflection = pointRotationHom d (Multiplicative.ofAdd i) *
              (pointRotationHom d (Multiplicative.ofAdd j))⁻¹ := by
            apply mul_right_cancel (b := pointRotationHom d (Multiplicative.ofAdd j))
            simpa [mul_assoc] using hxy.symm
          simpa [href] using hprod
  | sr i =>
      cases y with
      | r j =>
          exfalso
          apply d.reflection_reversing
          have hi := pointRotationHom_mem_orientationPreserving d
            (Multiplicative.ofAdd i)
          have hj := pointRotationHom_mem_orientationPreserving d
            (Multiplicative.ofAdd j)
          have hprod := (orientationPreservingPointGroup G).mul_mem hj
            ((orientationPreservingPointGroup G).inv_mem hi)
          change d.reflection * pointRotationHom d (Multiplicative.ofAdd i) =
            pointRotationHom d (Multiplicative.ofAdd j) at hxy
          have href : d.reflection = pointRotationHom d (Multiplicative.ofAdd j) *
              (pointRotationHom d (Multiplicative.ofAdd i))⁻¹ := by
            apply mul_right_cancel (b := pointRotationHom d (Multiplicative.ofAdd i))
            simpa [mul_assoc] using hxy
          simpa [href] using hprod
      | sr j =>
          congr 1
          apply Multiplicative.ofAdd.injective
          apply pointRotationHom_injective d
          change d.reflection * pointRotationHom d (Multiplicative.ofAdd i) =
            d.reflection * pointRotationHom d (Multiplicative.ofAdd j) at hxy
          exact mul_left_cancel hxy

/-- Canonical identification of the selected point group with the abstract finite dihedral
group. -/
noncomputable def pointDihedralEquiv (d : DihedralGenerators G) :
    DihedralGroup d.order.toNat ≃* pointGroup G.carrier :=
  MulEquiv.ofBijective (pointDihedralHom d)
    ⟨pointDihedralHom_injective d, pointDihedralHom_surjective d⟩

/-- Interpret canonical dihedral words using the selected affine lifts. -/
def wordLift (c : TwoReflectionExtensionData G d) :
    DihedralGroup d.order.toNat → G.carrier
  | .r i => c.rotationLiftHom (Multiplicative.ofAdd i)
  | .sr i => c.firstLift * c.rotationLiftHom (Multiplicative.ofAdd i)

/-- A canonical affine word projects to the corresponding abstract dihedral word. -/
@[simp]
theorem wordLift_projection (c : TwoReflectionExtensionData G d)
    (q : DihedralGroup d.order.toNat) :
    pointProjection G.carrier (c.wordLift q) = pointDihedralHom d q := by
  cases q with
  | r i =>
      exact c.rotationLiftHom_projection (Multiplicative.ofAdd i)
  | sr i =>
      change pointProjection G.carrier
          (c.firstLift * c.rotationLiftHom (Multiplicative.ofAdd i)) =
        d.reflection * pointRotationHom d (Multiplicative.ofAdd i)
      rw [map_mul, c.first_projection, c.rotationLiftHom_projection]

/-- The word lift is normalized at the identity. -/
@[simp]
theorem wordLift_one (c : TwoReflectionExtensionData G d) :
    c.wordLift 1 = 1 := by
  change c.rotationLiftHom (Multiplicative.ofAdd 0) = 1
  exact map_one c.rotationLiftHom

/-- The canonical normalized lift of an arbitrary point element. -/
def normalizedLift (c : TwoReflectionExtensionData G d)
    (q : pointGroup G.carrier) : G.carrier :=
  c.wordLift ((pointDihedralEquiv d).symm q)

/-- The canonical lift has the advertised point projection. -/
@[simp]
theorem normalizedLift_projection (c : TwoReflectionExtensionData G d)
    (q : pointGroup G.carrier) :
    pointProjection G.carrier (c.normalizedLift q) = q := by
  rw [normalizedLift, wordLift_projection]
  change pointDihedralEquiv d ((pointDihedralEquiv d).symm q) = q
  exact (pointDihedralEquiv d).apply_symm_apply q

/-- The canonical point section is normalized at one. -/
@[simp]
theorem normalizedLift_one (c : TwoReflectionExtensionData G d) :
    c.normalizedLift 1 = 1 := by
  simp [normalizedLift]

/-- The canonical word section as reusable `DihedralExtensionData`. -/
noncomputable def toDihedralExtensionData (c : TwoReflectionExtensionData G d) :
    DihedralExtensionData G where
  rotationGenerator := d.rotation.1
  rotationGenerator_ne_one := by
    intro h
    apply d.rotation_ne_one
    apply Subtype.ext
    exact h
  reflectionGenerator := d.reflection
  reflection_not_rotation := by
    intro h
    apply d.reflection_reversing
    obtain ⟨a, ha⟩ := h
    rw [← ha]
    exact (d.rotation ^ a).property
  reflection_sq := d.reflection_sq
  reflection_conjugates := by
    intro r
    have hr : r.1 ∈ orientationPreservingPointGroup G := by
      obtain ⟨a, ha⟩ := r.property
      rw [← ha]
      exact (d.rotation ^ a).property
    exact pointGroup_reversing_conjugates_to_inverse G d.reflection
      d.reflection_reversing ⟨r.1, hr⟩
  point_normal_form := by
    intro q
    rcases d.point_two_coset_normal_form q with
      ⟨r, hr, rfl⟩ | ⟨r, hr, rfl⟩
    · left
      obtain ⟨a, ha⟩ := hr
      exact ⟨a, congrArg Subtype.val ha⟩
    · right
      obtain ⟨a, ha⟩ := hr
      exact ⟨⟨r.1, ⟨a, congrArg Subtype.val ha⟩⟩, rfl⟩
  lift := c.normalizedLift
  lift_projection := c.normalizedLift_projection
  lift_one := c.normalizedLift_one

/-- The normalized section really chooses the supplied first reflection lift. -/
@[simp]
theorem normalizedLift_reflection (c : TwoReflectionExtensionData G d) :
    c.normalizedLift d.reflection = c.firstLift := by
  have hcoord : (pointDihedralEquiv d).symm d.reflection = DihedralGroup.sr 0 := by
    apply (pointDihedralEquiv d).injective
    rw [(pointDihedralEquiv d).apply_symm_apply]
    change d.reflection = d.reflection * pointRotationHom d (Multiplicative.ofAdd 0)
    change d.reflection = d.reflection * pointRotationHom d 1
    rw [map_one, mul_one]
  rw [normalizedLift, hcoord]
  change c.firstLift * c.rotationLiftHom (Multiplicative.ofAdd 0) = c.firstLift
  change c.firstLift * c.rotationLiftHom 1 = c.firstLift
  rw [map_one, mul_one]

/-! ## Translation/dihedral normal form -/

/-- Decode a translation followed by a canonical dihedral word. -/
def decode (c : TwoReflectionExtensionData G d) :
    translationVectors G.carrier × DihedralGroup d.order.toNat → G.carrier
  | (t, q) => translationElement G.carrier t * c.wordLift q

/-- The point projection of decoded coordinates is the corresponding dihedral point word. -/
@[simp]
theorem decode_projection (c : TwoReflectionExtensionData G d)
    (t : translationVectors G.carrier) (q : DihedralGroup d.order.toNat) :
    pointProjection G.carrier (c.decode (t, q)) = pointDihedralHom d q := by
  simp [decode]

/-- Translation/dihedral coordinates cover every motion. -/
theorem decode_surjective (c : TwoReflectionExtensionData G d) :
    Function.Surjective c.decode := by
  intro x
  let q : DihedralGroup d.order.toNat :=
    (pointDihedralEquiv d).symm (pointProjection G.carrier x)
  let y : G.carrier := x * (c.wordLift q)⁻¹
  have hyproj : pointProjection G.carrier y = 1 := by
    rw [show pointProjection G.carrier y =
        pointProjection G.carrier x *
          (pointProjection G.carrier (c.wordLift q))⁻¹ by simp [y]]
    rw [c.wordLift_projection]
    change pointProjection G.carrier x * (pointDihedralEquiv d q)⁻¹ = 1
    rw [show pointDihedralEquiv d q = pointProjection G.carrier x by
      simp [q]]
    simp
  have hyker : y ∈ translationSubgroup G.carrier := by
    rw [← pointProjection_ker]
    exact hyproj
  obtain ⟨t, ht⟩ :=
    (mem_translationSubgroup_iff_exists G.carrier y).mp hyker
  have hyt : y = translationElement G.carrier t := by
    apply Subtype.ext
    exact ht
  refine ⟨(t, q), ?_⟩
  change translationElement G.carrier t * c.wordLift q = x
  rw [← hyt]
  simp [y]

/-- Translation/dihedral coordinates are unique. -/
theorem decode_injective (c : TwoReflectionExtensionData G d) :
    Function.Injective c.decode := by
  rintro ⟨t, q⟩ ⟨u, r⟩ h
  have hqr : q = r := by
    apply (pointDihedralEquiv d).injective
    change pointDihedralHom d q = pointDihedralHom d r
    simpa using congrArg (pointProjection G.carrier) h
  subst r
  have htu : translationElement G.carrier t = translationElement G.carrier u :=
    mul_right_cancel h
  have : t = u := by
    apply Subtype.ext
    apply translation_injective
    exact congrArg (fun z : G.carrier => (z : EuclideanMotion Plane)) htu
  simp [this]

/-- Every motion has unique translation/dihedral coordinates. -/
noncomputable def decodeEquiv (c : TwoReflectionExtensionData G d) :
    translationVectors G.carrier × DihedralGroup d.order.toNat ≃ G.carrier :=
  Equiv.ofBijective c.decode ⟨c.decode_injective, c.decode_surjective⟩

/-! ## The word multiplication table -/

/-- The translation in the basic commutation rule `R * S = translation(cross) * S * R⁻¹`.
It is determined by the two reflection-square shifts. -/
def basicCrossShift (c : TwoReflectionExtensionData G d) :
    translationVectors G.carrier :=
  pointAction G.carrier d.rotation.1 (c.firstSquareShift + c.secondSquareShift)

/-- The elementary four-factor relation is exactly the sum of the two reflection squares. -/
theorem first_rotation_commutator (c : TwoReflectionExtensionData G d) :
    c.firstLift * c.rotationLift * c.firstLift⁻¹ * c.rotationLift =
      translationElement G.carrier (c.firstSquareShift + c.secondSquareShift) := by
  calc
    c.firstLift * c.rotationLift * c.firstLift⁻¹ * c.rotationLift =
        c.firstLift ^ 2 * c.secondLift ^ 2 := by
      simp only [rotationLift, pow_two]
      group
    _ = translationElement G.carrier c.firstSquareShift *
          translationElement G.carrier c.secondSquareShift := by
      rw [c.firstLift_sq, c.secondLift_sq]
    _ = translationElement G.carrier
          (c.firstSquareShift + c.secondSquareShift) := by
      rw [translationElement_add]

/-- The basic rule for commuting the rotation lift past the first reflection lift. -/
theorem rotationLift_mul_firstLift (c : TwoReflectionExtensionData G d) :
    c.rotationLift * c.firstLift =
      translationElement G.carrier c.basicCrossShift *
        c.firstLift * c.rotationLift⁻¹ := by
  have hconj : c.rotationLift *
        translationElement G.carrier (c.firstSquareShift + c.secondSquareShift) *
          c.rotationLift⁻¹ =
      translationElement G.carrier c.basicCrossShift := by
    rw [conjugate_translationElement]
    simp [basicCrossShift]
  have hfour : c.rotationLift * c.firstLift * c.rotationLift * c.firstLift⁻¹ =
      translationElement G.carrier c.basicCrossShift := by
    calc
      c.rotationLift * c.firstLift * c.rotationLift * c.firstLift⁻¹ =
          c.rotationLift *
            (c.firstLift * c.rotationLift * c.firstLift⁻¹ * c.rotationLift) *
              c.rotationLift⁻¹ := by group
      _ = c.rotationLift *
            translationElement G.carrier
              (c.firstSquareShift + c.secondSquareShift) *
              c.rotationLift⁻¹ := by
        rw [c.first_rotation_commutator]
      _ = translationElement G.carrier c.basicCrossShift := hconj
  calc
    c.rotationLift * c.firstLift =
        (c.rotationLift * c.firstLift * c.rotationLift * c.firstLift⁻¹) *
          (c.firstLift * c.rotationLift⁻¹) := by group
    _ = translationElement G.carrier c.basicCrossShift *
          c.firstLift * c.rotationLift⁻¹ := by
      rw [hfour]
      group

/-- Move a translation through a natural power of the rotation lift. -/
theorem rotationLift_pow_mul_translation (c : TwoReflectionExtensionData G d)
    (k : ℕ) (t : translationVectors G.carrier) :
    c.rotationLift ^ k * translationElement G.carrier t =
      translationElement G.carrier
          (pointAction G.carrier (d.rotation.1 ^ k) t) * c.rotationLift ^ k := by
  calc
    c.rotationLift ^ k * translationElement G.carrier t =
        (c.rotationLift ^ k * translationElement G.carrier t *
          (c.rotationLift ^ k)⁻¹) * c.rotationLift ^ k := by group
    _ = translationElement G.carrier
          (pointAction G.carrier
            (pointProjection G.carrier (c.rotationLift ^ k)) t) *
          c.rotationLift ^ k := by
      rw [conjugate_translationElement]
    _ = translationElement G.carrier
          (pointAction G.carrier (d.rotation.1 ^ k) t) * c.rotationLift ^ k := by
      rw [map_pow, c.rotationLift_projection]

/-- Recursively accumulated cross shift for the word `R^k * S`. -/
def crossShiftNat (c : TwoReflectionExtensionData G d) : ℕ → translationVectors G.carrier
  | 0 => 0
  | k + 1 => pointAction G.carrier (d.rotation.1 ^ k) c.basicCrossShift +
      c.crossShiftNat k

/-- Natural powers obey the canonical reflection-commutation rule. -/
theorem rotationLift_pow_mul_firstLift (c : TwoReflectionExtensionData G d) (k : ℕ) :
    c.rotationLift ^ k * c.firstLift =
      translationElement G.carrier (c.crossShiftNat k) *
        c.firstLift * (c.rotationLift ^ k)⁻¹ := by
  induction k with
  | zero =>
      rw [pow_zero, crossShiftNat]
      have hzero : translationElement G.carrier (0 : translationVectors G.carrier) = 1 := by
        apply Subtype.ext
        exact translation_zero
      rw [hzero]
      simp
  | succ k ih =>
      calc
        c.rotationLift ^ (k + 1) * c.firstLift =
            c.rotationLift ^ k * (c.rotationLift * c.firstLift) := by
          rw [pow_succ]
          group
        _ =
            c.rotationLift ^ k *
              (translationElement G.carrier c.basicCrossShift *
                c.firstLift * c.rotationLift⁻¹) := by
          rw [c.rotationLift_mul_firstLift]
        _ = (c.rotationLift ^ k *
              translationElement G.carrier c.basicCrossShift) *
                c.firstLift * c.rotationLift⁻¹ := by group
        _ = (translationElement G.carrier
              (pointAction G.carrier (d.rotation.1 ^ k) c.basicCrossShift) *
                c.rotationLift ^ k) * c.firstLift * c.rotationLift⁻¹ := by
          rw [c.rotationLift_pow_mul_translation]
        _ = translationElement G.carrier
              (pointAction G.carrier (d.rotation.1 ^ k) c.basicCrossShift) *
                (c.rotationLift ^ k * c.firstLift) * c.rotationLift⁻¹ := by group
        _ = translationElement G.carrier
              (pointAction G.carrier (d.rotation.1 ^ k) c.basicCrossShift) *
                (translationElement G.carrier (c.crossShiftNat k) *
                  c.firstLift * (c.rotationLift ^ k)⁻¹) *
                    c.rotationLift⁻¹ := by rw [ih]
        _ = translationElement G.carrier (c.crossShiftNat (k + 1)) *
              c.firstLift * (c.rotationLift ^ (k + 1))⁻¹ := by
          rw [crossShiftNat, translationElement_add]
          group

/-- A cyclic rotation word is represented by the power of its least natural residue. -/
theorem rotationLiftHom_eq_pow_val (c : TwoReflectionExtensionData G d)
    (i : ZMod d.order.toNat) :
    c.rotationLiftHom (Multiplicative.ofAdd i) = c.rotationLift ^ i.val := by
  have hn : d.order.toNat ≠ 0 := by cases d.order <;> decide
  letI : NeZero d.order.toNat := ⟨hn⟩
  conv_lhs => rw [← ZMod.natCast_zmod_val i]
  have hcast : (i.val : ZMod d.order.toNat) =
      ((i.val : ℤ) : ZMod d.order.toNat) := by simp
  rw [hcast]
  unfold rotationLiftHom
  rw [zmodPowerHom_ofAdd_intCast, zpow_natCast]

/-- Cross shift attached to a finite cyclic rotation coordinate. -/
def crossShift (c : TwoReflectionExtensionData G d) (i : ZMod d.order.toNat) :
    translationVectors G.carrier :=
  c.crossShiftNat i.val

/-- The finite cyclic word version of the reflection-commutation rule. -/
theorem rotationWord_mul_firstLift (c : TwoReflectionExtensionData G d)
    (i : ZMod d.order.toNat) :
    c.rotationLiftHom (Multiplicative.ofAdd i) * c.firstLift =
      translationElement G.carrier (c.crossShift i) * c.firstLift *
        c.rotationLiftHom (Multiplicative.ofAdd (-i)) := by
  rw [c.rotationLiftHom_eq_pow_val]
  rw [crossShift, c.rotationLift_pow_mul_firstLift]
  have hinv : c.rotationLiftHom (Multiplicative.ofAdd (-i)) =
      (c.rotationLift ^ i.val)⁻¹ := by
    rw [show Multiplicative.ofAdd (-i) =
        (Multiplicative.ofAdd i)⁻¹ by rfl, map_inv, c.rotationLiftHom_eq_pow_val]
  rw [hinv]

/-- The zero translation vector gives the identity motion. -/
@[simp]
theorem translationElement_zero_twoReflection :
    translationElement G.carrier (0 : translationVectors G.carrier) = 1 := by
  apply Subtype.ext
  exact translation_zero

/-- Move a translation past an arbitrary canonical dihedral word. -/
theorem wordLift_mul_translation (c : TwoReflectionExtensionData G d)
    (q : DihedralGroup d.order.toNat) (t : translationVectors G.carrier) :
    c.wordLift q * translationElement G.carrier t =
      translationElement G.carrier
        (pointAction G.carrier (pointDihedralHom d q) t) * c.wordLift q := by
  calc
    c.wordLift q * translationElement G.carrier t =
        (c.wordLift q * translationElement G.carrier t * (c.wordLift q)⁻¹) *
          c.wordLift q := by group
    _ = translationElement G.carrier
          (pointAction G.carrier (pointProjection G.carrier (c.wordLift q)) t) *
            c.wordLift q := by
      rw [conjugate_translationElement]
    _ = translationElement G.carrier
          (pointAction G.carrier (pointDihedralHom d q) t) * c.wordLift q := by
      rw [c.wordLift_projection]

/-- Move a translation past the selected first reflection lift. -/
theorem firstLift_mul_translation (c : TwoReflectionExtensionData G d)
    (t : translationVectors G.carrier) :
    c.firstLift * translationElement G.carrier t =
      translationElement G.carrier (pointAction G.carrier d.reflection t) *
        c.firstLift := by
  calc
    c.firstLift * translationElement G.carrier t =
        (c.firstLift * translationElement G.carrier t * c.firstLift⁻¹) *
          c.firstLift := by group
    _ = translationElement G.carrier
          (pointAction G.carrier (pointProjection G.carrier c.firstLift) t) *
            c.firstLift := by
      rw [conjugate_translationElement]
    _ = translationElement G.carrier (pointAction G.carrier d.reflection t) *
          c.firstLift := by rw [c.first_projection]

/-- Translation factor in the multiplication table of canonical dihedral words. -/
def wordFactor (c : TwoReflectionExtensionData G d) :
    DihedralGroup d.order.toNat → DihedralGroup d.order.toNat →
      translationVectors G.carrier
  | .r _, .r _ => 0
  | .r i, .sr _ => c.crossShift i
  | .sr _, .r _ => 0
  | .sr i, .sr _ =>
      pointAction G.carrier d.reflection (c.crossShift i) + c.firstSquareShift

/-- Multiplication of canonical words is controlled by `wordFactor`. -/
theorem wordLift_mul (c : TwoReflectionExtensionData G d)
    (q r : DihedralGroup d.order.toNat) :
    c.wordLift q * c.wordLift r =
      translationElement G.carrier (c.wordFactor q r) * c.wordLift (q * r) := by
  cases q with
  | r i =>
      cases r with
      | r j =>
          simp only [wordLift, wordFactor, DihedralGroup.r_mul_r,
            translationElement_zero_twoReflection, one_mul]
          rw [← map_mul]
          rfl
      | sr j =>
          change c.rotationLiftHom (Multiplicative.ofAdd i) *
              (c.firstLift * c.rotationLiftHom (Multiplicative.ofAdd j)) =
            translationElement G.carrier (c.crossShift i) *
              (c.firstLift *
                c.rotationLiftHom (Multiplicative.ofAdd (j - i)))
          calc
            c.rotationLiftHom (Multiplicative.ofAdd i) *
                  (c.firstLift * c.rotationLiftHom (Multiplicative.ofAdd j)) =
                (c.rotationLiftHom (Multiplicative.ofAdd i) * c.firstLift) *
                  c.rotationLiftHom (Multiplicative.ofAdd j) := by group
            _ = (translationElement G.carrier (c.crossShift i) * c.firstLift *
                  c.rotationLiftHom (Multiplicative.ofAdd (-i))) *
                    c.rotationLiftHom (Multiplicative.ofAdd j) := by
              rw [c.rotationWord_mul_firstLift]
            _ = translationElement G.carrier (c.crossShift i) *
                  (c.firstLift *
                    (c.rotationLiftHom (Multiplicative.ofAdd (-i)) *
                      c.rotationLiftHom (Multiplicative.ofAdd j))) := by group
            _ = translationElement G.carrier (c.crossShift i) *
                  (c.firstLift *
                    c.rotationLiftHom (Multiplicative.ofAdd (j - i))) := by
              have hrot : c.rotationLiftHom (Multiplicative.ofAdd (-i)) *
                    c.rotationLiftHom (Multiplicative.ofAdd j) =
                  c.rotationLiftHom (Multiplicative.ofAdd (j - i)) := by
                rw [← map_mul]
                congr 1
                apply Multiplicative.toAdd.injective
                change -i + j = j - i
                abel
              rw [hrot]
  | sr i =>
      cases r with
      | r j =>
          simp only [wordLift, wordFactor, DihedralGroup.sr_mul_r,
            translationElement_zero_twoReflection, one_mul]
          rw [mul_assoc, ← map_mul]
          rfl
      | sr j =>
          change (c.firstLift * c.rotationLiftHom (Multiplicative.ofAdd i)) *
              (c.firstLift * c.rotationLiftHom (Multiplicative.ofAdd j)) =
            translationElement G.carrier
                (pointAction G.carrier d.reflection (c.crossShift i) +
                  c.firstSquareShift) *
              c.rotationLiftHom (Multiplicative.ofAdd (j - i))
          calc
            (c.firstLift * c.rotationLiftHom (Multiplicative.ofAdd i)) *
                  (c.firstLift * c.rotationLiftHom (Multiplicative.ofAdd j)) =
                c.firstLift *
                  (c.rotationLiftHom (Multiplicative.ofAdd i) * c.firstLift) *
                    c.rotationLiftHom (Multiplicative.ofAdd j) := by group
            _ = c.firstLift *
                  (translationElement G.carrier (c.crossShift i) * c.firstLift *
                    c.rotationLiftHom (Multiplicative.ofAdd (-i))) *
                      c.rotationLiftHom (Multiplicative.ofAdd j) := by
              rw [c.rotationWord_mul_firstLift]
            _ = (c.firstLift * translationElement G.carrier (c.crossShift i)) *
                  c.firstLift *
                    (c.rotationLiftHom (Multiplicative.ofAdd (-i)) *
                      c.rotationLiftHom (Multiplicative.ofAdd j)) := by group
            _ = (translationElement G.carrier
                    (pointAction G.carrier d.reflection (c.crossShift i)) *
                      c.firstLift) * c.firstLift *
                    (c.rotationLiftHom (Multiplicative.ofAdd (-i)) *
                      c.rotationLiftHom (Multiplicative.ofAdd j)) := by
              rw [c.firstLift_mul_translation]
            _ = translationElement G.carrier
                    (pointAction G.carrier d.reflection (c.crossShift i)) *
                  (c.firstLift ^ 2) *
                    (c.rotationLiftHom (Multiplicative.ofAdd (-i)) *
                      c.rotationLiftHom (Multiplicative.ofAdd j)) := by
              simp only [pow_two]
              group
            _ = translationElement G.carrier
                    (pointAction G.carrier d.reflection (c.crossShift i)) *
                  translationElement G.carrier c.firstSquareShift *
                    (c.rotationLiftHom (Multiplicative.ofAdd (-i)) *
                      c.rotationLiftHom (Multiplicative.ofAdd j)) := by
              rw [c.firstLift_sq]
            _ = translationElement G.carrier
                    (pointAction G.carrier d.reflection (c.crossShift i) +
                      c.firstSquareShift) *
                  c.rotationLiftHom (Multiplicative.ofAdd (j - i)) := by
              rw [translationElement_add]
              have hrot : c.rotationLiftHom (Multiplicative.ofAdd (-i)) *
                    c.rotationLiftHom (Multiplicative.ofAdd j) =
                  c.rotationLiftHom (Multiplicative.ofAdd (j - i)) := by
                rw [← map_mul]
                congr 1
                apply Multiplicative.toAdd.injective
                change -i + j = j - i
                abel
              rw [hrot]

/-- Multiplication in translation/dihedral coordinates. -/
theorem decode_mul (c : TwoReflectionExtensionData G d)
    (t u : translationVectors G.carrier)
    (q r : DihedralGroup d.order.toNat) :
    c.decode (t, q) * c.decode (u, r) =
      c.decode
        (t + pointAction G.carrier (pointDihedralHom d q) u + c.wordFactor q r,
          q * r) := by
  change (translationElement G.carrier t * c.wordLift q) *
      (translationElement G.carrier u * c.wordLift r) =
    translationElement G.carrier
        (t + pointAction G.carrier (pointDihedralHom d q) u + c.wordFactor q r) *
      c.wordLift (q * r)
  calc
    (translationElement G.carrier t * c.wordLift q) *
        (translationElement G.carrier u * c.wordLift r) =
      translationElement G.carrier t *
        (c.wordLift q * translationElement G.carrier u) * c.wordLift r := by group
    _ = translationElement G.carrier t *
        (translationElement G.carrier
          (pointAction G.carrier (pointDihedralHom d q) u) * c.wordLift q) *
            c.wordLift r := by rw [c.wordLift_mul_translation]
    _ = (translationElement G.carrier t *
          translationElement G.carrier
            (pointAction G.carrier (pointDihedralHom d q) u)) *
        (c.wordLift q * c.wordLift r) := by group
    _ = translationElement G.carrier
          (t + pointAction G.carrier (pointDihedralHom d q) u) *
        (translationElement G.carrier (c.wordFactor q r) * c.wordLift (q * r)) := by
      rw [translationElement_add, c.wordLift_mul]
    _ = translationElement G.carrier
          (t + pointAction G.carrier (pointDihedralHom d q) u + c.wordFactor q r) *
        c.wordLift (q * r) := by
      rw [← mul_assoc, ← translationElement_add]

/-! ## Comparison of two-reflection extension data -/

/-- The point-rotation coordinate is the least-natural-residue power of the selected generator. -/
theorem pointRotationHom_eq_pow_val (d : DihedralGenerators G)
    (i : ZMod d.order.toNat) :
    pointRotationHom d (Multiplicative.ofAdd i) = d.rotation.1 ^ i.val := by
  have hn : d.order.toNat ≠ 0 := by cases d.order <;> decide
  letI : NeZero d.order.toNat := ⟨hn⟩
  conv_lhs => rw [← ZMod.natCast_zmod_val i]
  have hcast : (i.val : ZMod d.order.toNat) =
      ((i.val : ℤ) : ZMod d.order.toNat) := by simp
  rw [hcast]
  unfold pointRotationHom
  rw [zmodPowerHom_ofAdd_intCast, zpow_natCast]

/-- The point word underlying a dihedral coordinate, expressed without tying the coordinate
modulus to a particular `DihedralGenerators` structure. -/
def dihedralPointWord {K : PlaneGroup}
    (rotation reflection : pointGroup K.carrier) {n : ℕ} :
    DihedralGroup n → pointGroup K.carrier
  | .r i => rotation ^ i.val
  | .sr i => reflection * rotation ^ i.val

/-- Reindexing an abstract dihedral coordinate does not change its rotation/reflection word. -/
theorem dihedralPointWord_cast
    {K : PlaneGroup} (rotation reflection : pointGroup K.carrier)
    {n m : ℕ} (h : n = m) (q : DihedralGroup n) :
    dihedralPointWord rotation reflection ((MulEquiv.cast h) q) =
      dihedralPointWord rotation reflection q := by
  cases h
  rfl

/-- The canonical point homomorphism is evaluation of the corresponding abstract point word. -/
theorem pointDihedralHom_eq_dihedralPointWord
    (d : DihedralGenerators G) (q : DihedralGroup d.order.toNat) :
    pointDihedralHom d q = dihedralPointWord d.rotation.1 d.reflection q := by
  cases q with
  | r i =>
      rw [pointDihedralHom_r, pointRotationHom_eq_pow_val]
      rfl
  | sr i =>
      rw [pointDihedralHom_sr, pointRotationHom_eq_pow_val]
      rfl

/-- Cast abstract dihedral coordinates along equality of their typed rotation orders. -/
def dihedralCoordinateEquiv
    {G H : PlaneGroup} (dG : DihedralGenerators G) (dH : DihedralGenerators H)
    (horder : dG.order.toNat = dH.order.toNat) :
    DihedralGroup dG.order.toNat ≃* DihedralGroup dH.order.toNat :=
  MulEquiv.cast (M := DihedralGroup) horder

/-- The canonical point-group equivalence induced by matched typed rotation orders. -/
noncomputable def pointEquivOfDihedralOrder
    {G H : PlaneGroup} (dG : DihedralGenerators G) (dH : DihedralGenerators H)
    (horder : dG.order.toNat = dH.order.toNat) :
    pointGroup G.carrier ≃* pointGroup H.carrier :=
  (pointDihedralEquiv dG).symm.trans
    ((dihedralCoordinateEquiv dG dH horder).trans (pointDihedralEquiv dH))

/-- The normalized point section evaluated on a canonical point word is the corresponding
canonical affine word. -/
@[simp]
theorem normalizedLift_pointDihedralHom (c : TwoReflectionExtensionData G d)
    (q : DihedralGroup d.order.toNat) :
    c.normalizedLift (pointDihedralHom d q) = c.wordLift q := by
  change c.wordLift
      ((pointDihedralEquiv d).symm ((pointDihedralEquiv d) q)) = c.wordLift q
  rw [(pointDihedralEquiv d).symm_apply_apply]

/-- The generic normalized factor attached to the canonical point section is the explicit
two-reflection word factor. -/
theorem dihedralFactor_toDihedralExtensionData
    (c : TwoReflectionExtensionData G d)
    (q r : DihedralGroup d.order.toNat) :
    dihedralFactor c.toDihedralExtensionData
        (pointDihedralHom d q) (pointDihedralHom d r) = c.wordFactor q r := by
  have hgeneric := dihedralLift_mul_lift c.toDihedralExtensionData
    (pointDihedralHom d q) (pointDihedralHom d r)
  have hword := c.wordLift_mul q r
  change c.normalizedLift (pointDihedralHom d q) *
        c.normalizedLift (pointDihedralHom d r) =
      translationElement G.carrier
          (dihedralFactor c.toDihedralExtensionData
            (pointDihedralHom d q) (pointDihedralHom d r)) *
        c.normalizedLift (pointDihedralHom d q * pointDihedralHom d r) at hgeneric
  rw [normalizedLift_pointDihedralHom, normalizedLift_pointDihedralHom] at hgeneric
  have hmul : pointDihedralHom d q * pointDihedralHom d r =
      pointDihedralHom d (q * r) := by rw [map_mul]
  rw [hmul, normalizedLift_pointDihedralHom] at hgeneric
  have htranslations :
      translationElement G.carrier
          (dihedralFactor c.toDihedralExtensionData
            (pointDihedralHom d q) (pointDihedralHom d r)) =
        translationElement G.carrier (c.wordFactor q r) := by
    apply mul_right_cancel (b := c.wordLift (q * r))
    exact hgeneric.symm.trans hword
  apply Subtype.ext
  apply translation_injective
  exact congrArg (fun z : G.carrier => (z : EuclideanMotion Plane)) htranslations

/-- Exact square shifts and the rotation action determine the elementary cross shift. -/
theorem basicCrossShift_natural
    {G H : PlaneGroup} {dG : DihedralGenerators G} {dH : DihedralGenerators H}
    (cG : TwoReflectionExtensionData G dG) (cH : TwoReflectionExtensionData H dH)
    (eT : translationVectors G.carrier ≃+ translationVectors H.carrier)
    (hrotation : ∀ t : translationVectors G.carrier,
      eT (pointAction G.carrier dG.rotation.1 t) =
        pointAction H.carrier dH.rotation.1 (eT t))
    (hfirst : eT cG.firstSquareShift = cH.firstSquareShift)
    (hsecond : eT cG.secondSquareShift = cH.secondSquareShift) :
    eT cG.basicCrossShift = cH.basicCrossShift := by
  rw [basicCrossShift, basicCrossShift, hrotation, map_add, hfirst, hsecond]

/-- The recursively accumulated cross shift is natural under matched generator actions and
exact square shifts. -/
theorem crossShiftNat_natural
    {G H : PlaneGroup} {dG : DihedralGenerators G} {dH : DihedralGenerators H}
    (cG : TwoReflectionExtensionData G dG) (cH : TwoReflectionExtensionData H dH)
    (eT : translationVectors G.carrier ≃+ translationVectors H.carrier)
    (hrotation : ∀ t : translationVectors G.carrier,
      eT (pointAction G.carrier dG.rotation.1 t) =
        pointAction H.carrier dH.rotation.1 (eT t))
    (hfirst : eT cG.firstSquareShift = cH.firstSquareShift)
    (hsecond : eT cG.secondSquareShift = cH.secondSquareShift)
    (k : ℕ) :
    eT (cG.crossShiftNat k) = cH.crossShiftNat k := by
  induction k with
  | zero => simp [crossShiftNat]
  | succ k ih =>
      rw [crossShiftNat, crossShiftNat, map_add]
      rw [pointAction_pow_intertwining eT dG.rotation.1 dH.rotation.1
        hrotation k cG.basicCrossShift]
      rw [basicCrossShift_natural cG cH eT hrotation hfirst hsecond, ih]

/-- The complete canonical word-factor table is natural under matched typed order, generator
actions, and the two exact reflection-square shifts. -/
theorem wordFactor_natural
    {G H : PlaneGroup} {dG : DihedralGenerators G} {dH : DihedralGenerators H}
    (cG : TwoReflectionExtensionData G dG) (cH : TwoReflectionExtensionData H dH)
    (eT : translationVectors G.carrier ≃+ translationVectors H.carrier)
    (horder : dG.order.toNat = dH.order.toNat)
    (hrotation : ∀ t : translationVectors G.carrier,
      eT (pointAction G.carrier dG.rotation.1 t) =
        pointAction H.carrier dH.rotation.1 (eT t))
    (hreflection : ∀ t : translationVectors G.carrier,
      eT (pointAction G.carrier dG.reflection t) =
        pointAction H.carrier dH.reflection (eT t))
    (hfirst : eT cG.firstSquareShift = cH.firstSquareShift)
    (hsecond : eT cG.secondSquareShift = cH.secondSquareShift)
    (q r : DihedralGroup dG.order.toNat) :
    eT (cG.wordFactor q r) =
      cH.wordFactor (dihedralCoordinateEquiv dG dH horder q)
        (dihedralCoordinateEquiv dG dH horder r) := by
  have htyped : dG.order = dH.order := by
    cases hg : dG.order <;> cases hh : dH.order <;>
      simp_all [DihedralRotationOrder.toNat]
  cases dG
  cases dH
  dsimp only [DihedralGenerators.order] at *
  cases htyped
  have horder_refl : horder = rfl := Subsingleton.elim _ _
  cases horder_refl
  cases q with
  | r i =>
      cases r with
      | r j => simp [wordFactor, dihedralCoordinateEquiv]
      | sr j =>
          change eT (cG.crossShiftNat i.val) = cH.crossShiftNat i.val
          exact crossShiftNat_natural cG cH eT hrotation hfirst hsecond i.val
  | sr i =>
      cases r with
      | r j => simp [wordFactor, dihedralCoordinateEquiv]
      | sr j =>
          simp only [wordFactor, dihedralCoordinateEquiv, crossShift]
          rw [map_add, hreflection,
            crossShiftNat_natural cG cH eT hrotation hfirst hsecond, hfirst]
          simp [MulEquiv.cast, Equiv.cast]

/-- The canonical point equivalence acts on abstract dihedral coordinates by the corresponding
coordinate cast. -/
@[simp]
theorem pointEquivOfDihedralOrder_pointDihedralHom
    {G H : PlaneGroup} (dG : DihedralGenerators G) (dH : DihedralGenerators H)
    (horder : dG.order.toNat = dH.order.toNat)
    (q : DihedralGroup dG.order.toNat) :
    pointEquivOfDihedralOrder dG dH horder (pointDihedralHom dG q) =
      pointDihedralHom dH (dihedralCoordinateEquiv dG dH horder q) := by
  change (pointDihedralEquiv dH)
      (dihedralCoordinateEquiv dG dH horder
        ((pointDihedralEquiv dG).symm ((pointDihedralEquiv dG) q))) = _
  rw [(pointDihedralEquiv dG).symm_apply_apply]
  rfl

/-- Matching the rotation and first-reflection actions intertwines the point action of every
canonical dihedral coordinate. -/
theorem pointDihedralAction_natural
    {G H : PlaneGroup} (dG : DihedralGenerators G) (dH : DihedralGenerators H)
    (eT : translationVectors G.carrier ≃+ translationVectors H.carrier)
    (horder : dG.order.toNat = dH.order.toNat)
    (hrotation : ∀ t : translationVectors G.carrier,
      eT (pointAction G.carrier dG.rotation.1 t) =
        pointAction H.carrier dH.rotation.1 (eT t))
    (hreflection : ∀ t : translationVectors G.carrier,
      eT (pointAction G.carrier dG.reflection t) =
        pointAction H.carrier dH.reflection (eT t))
    (q : DihedralGroup dG.order.toNat) (t : translationVectors G.carrier) :
    eT (pointAction G.carrier (pointDihedralHom dG q) t) =
      pointAction H.carrier
        (pointDihedralHom dH (dihedralCoordinateEquiv dG dH horder q)) (eT t) := by
  rw [pointDihedralHom_eq_dihedralPointWord,
    pointDihedralHom_eq_dihedralPointWord]
  unfold dihedralCoordinateEquiv
  rw [dihedralPointWord_cast]
  cases q with
  | r i =>
      exact pointAction_pow_intertwining eT dG.rotation.1 dH.rotation.1
        hrotation i.val t
  | sr i =>
      change eT
          (pointAction G.carrier (dG.reflection * dG.rotation.1 ^ i.val) t) =
        pointAction H.carrier (dH.reflection * dH.rotation.1 ^ i.val) (eT t)
      rw [pointAction_mul, pointAction_mul]
      rw [hreflection]
      exact congrArg (pointAction H.carrier _) <|
        pointAction_pow_intertwining eT dG.rotation.1 dH.rotation.1
          hrotation i.val t

/-- Equality of the translation action and the two exact adjacent-reflection square shifts
determines the whole dihedral extension. -/
noncomputable def twoReflectionExtensionIsoExact
    (G H : PlaneGroup)
    (dG : DihedralGenerators G) (dH : DihedralGenerators H)
    (cG : TwoReflectionExtensionData G dG) (cH : TwoReflectionExtensionData H dH)
    (eT : translationVectors G.carrier ≃+ translationVectors H.carrier)
    (horder : dG.order.toNat = dH.order.toNat)
    (hrotation : ∀ t : translationVectors G.carrier,
      eT (pointAction G.carrier dG.rotation.1 t) =
        pointAction H.carrier dH.rotation.1 (eT t))
    (hreflection : ∀ t : translationVectors G.carrier,
      eT (pointAction G.carrier dG.reflection t) =
        pointAction H.carrier dH.reflection (eT t))
    (hfirst : eT cG.firstSquareShift = cH.firstSquareShift)
    (hsecond : eT cG.secondSquareShift = cH.secondSquareShift) :
    TranslationPreservingIso G H := by
  let eP := pointEquivOfDihedralOrder dG dH horder
  apply dihedralExtensionIso G H cG.toDihedralExtensionData
    cH.toDihedralExtensionData eT eP
  · intro q t
    let z : DihedralGroup dG.order.toNat :=
      (pointDihedralEquiv dG).symm q
    have hq : q = pointDihedralHom dG z := by
      change q = pointDihedralEquiv dG z
      exact ((pointDihedralEquiv dG).apply_symm_apply q).symm
    rw [hq]
    change eT (pointAction G.carrier (pointDihedralHom dG z) t) =
      pointAction H.carrier
        (pointEquivOfDihedralOrder dG dH horder (pointDihedralHom dG z)) (eT t)
    rw [pointEquivOfDihedralOrder_pointDihedralHom]
    exact pointDihedralAction_natural dG dH eT horder hrotation hreflection z t
  · intro q r
    let z : DihedralGroup dG.order.toNat :=
      (pointDihedralEquiv dG).symm q
    let w : DihedralGroup dG.order.toNat :=
      (pointDihedralEquiv dG).symm r
    have hq : q = pointDihedralHom dG z := by
      change q = pointDihedralEquiv dG z
      exact ((pointDihedralEquiv dG).apply_symm_apply q).symm
    have hr : r = pointDihedralHom dG w := by
      change r = pointDihedralEquiv dG w
      exact ((pointDihedralEquiv dG).apply_symm_apply r).symm
    rw [hq, hr]
    change eT
        (dihedralFactor cG.toDihedralExtensionData
          (pointDihedralHom dG z) (pointDihedralHom dG w)) =
      dihedralFactor cH.toDihedralExtensionData
        (pointEquivOfDihedralOrder dG dH horder (pointDihedralHom dG z))
        (pointEquivOfDihedralOrder dG dH horder (pointDihedralHom dG w))
    rw [pointEquivOfDihedralOrder_pointDihedralHom,
      pointEquivOfDihedralOrder_pointDihedralHom,
      dihedralFactor_toDihedralExtensionData,
      dihedralFactor_toDihedralExtensionData]
    exact wordFactor_natural cG cH eT horder hrotation hreflection
      hfirst hsecond z w

/-! ## Simultaneous lift adjustment and quotient-valued comparison -/

/-- Independently left-translate the two adjacent reflection lifts.  Their product remains the
rotation lift; no extra compatibility datum is needed. -/
def adjust (c : TwoReflectionExtensionData G d)
    (u v : translationVectors G.carrier) : TwoReflectionExtensionData G d where
  firstLift := translationElement G.carrier u * c.firstLift
  first_projection := by
    rw [map_mul, pointProjection_translationElement, c.first_projection, one_mul]
  secondLift := translationElement G.carrier v * c.secondLift
  second_projection := by
    rw [map_mul, pointProjection_translationElement, c.second_projection, one_mul]

/-- The lift-difference translation from the old first lift to its adjustment is the selected
adjustment vector. -/
theorem liftDifferenceTranslation_first_adjust
    (c : TwoReflectionExtensionData G d) (u v : translationVectors G.carrier) :
    liftDifferenceTranslation G d.reflection c.firstLift (c.adjust u v).firstLift
        c.first_projection (c.adjust u v).first_projection = u := by
  apply Subtype.ext
  apply translation_injective
  apply mul_right_cancel (b := (c.firstLift : EuclideanMotion Plane))
  simpa [adjust] using translation_liftDifference_mul G d.reflection
    c.firstLift (c.adjust u v).firstLift c.first_projection
      (c.adjust u v).first_projection

/-- The analogous lift-difference formula for the second adjacent reflection. -/
theorem liftDifferenceTranslation_second_adjust
    (c : TwoReflectionExtensionData G d) (u v : translationVectors G.carrier) :
    liftDifferenceTranslation G d.secondReflection c.secondLift (c.adjust u v).secondLift
        c.second_projection (c.adjust u v).second_projection = v := by
  apply Subtype.ext
  apply translation_injective
  apply mul_right_cancel (b := (c.secondLift : EuclideanMotion Plane))
  simpa [adjust] using translation_liftDifference_mul G d.secondReflection
    c.secondLift (c.adjust u v).secondLift c.second_projection
      (c.adjust u v).second_projection

/-- Adjusting the first reflection lift adds the corresponding order-two norm to its exact
square shift. -/
theorem firstSquareShift_adjust
    (c : TwoReflectionExtensionData G d) (u v : translationVectors G.carrier) :
    (c.adjust u v).firstSquareShift =
      finiteNormHom G d.reflection 2 u + c.firstSquareShift := by
  have hsub := liftPowerTranslation_sub_eq_norm G d.reflection 2 d.reflection_sq
    c.firstLift (c.adjust u v).firstLift c.first_projection
      (c.adjust u v).first_projection
  change (c.adjust u v).firstSquareShift - c.firstSquareShift =
    finiteNormHom G d.reflection 2
      (liftDifferenceTranslation G d.reflection c.firstLift
        (c.adjust u v).firstLift c.first_projection
          (c.adjust u v).first_projection) at hsub
  rw [c.liftDifferenceTranslation_first_adjust u v] at hsub
  rw [← hsub]
  abel

/-- Adjusting the second reflection lift adds its order-two norm to the second exact square
shift. -/
theorem secondSquareShift_adjust
    (c : TwoReflectionExtensionData G d) (u v : translationVectors G.carrier) :
    (c.adjust u v).secondSquareShift =
      finiteNormHom G d.secondReflection 2 v + c.secondSquareShift := by
  have hsub := liftPowerTranslation_sub_eq_norm G d.secondReflection 2
    d.secondReflection_sq c.secondLift (c.adjust u v).secondLift c.second_projection
      (c.adjust u v).second_projection
  change (c.adjust u v).secondSquareShift - c.secondSquareShift =
    finiteNormHom G d.secondReflection 2
      (liftDifferenceTranslation G d.secondReflection c.secondLift
        (c.adjust u v).secondLift c.second_projection
          (c.adjust u v).second_projection) at hsub
  rw [c.liftDifferenceTranslation_second_adjust u v] at hsub
  rw [← hsub]
  abel

/-- Intertwining the selected rotation and first-reflection actions also intertwines the action
of the adjacent second reflection. -/
theorem secondReflectionAction_natural
    {G H : PlaneGroup} (dG : DihedralGenerators G) (dH : DihedralGenerators H)
    (eT : translationVectors G.carrier ≃+ translationVectors H.carrier)
    (hrotation : ∀ t : translationVectors G.carrier,
      eT (pointAction G.carrier dG.rotation.1 t) =
        pointAction H.carrier dH.rotation.1 (eT t))
    (hreflection : ∀ t : translationVectors G.carrier,
      eT (pointAction G.carrier dG.reflection t) =
        pointAction H.carrier dH.reflection (eT t))
    (t : translationVectors G.carrier) :
    eT (pointAction G.carrier dG.secondReflection t) =
      pointAction H.carrier dH.secondReflection (eT t) := by
  rw [DihedralGenerators.secondReflection, DihedralGenerators.secondReflection,
    pointAction_mul, pointAction_mul, hreflection, hrotation]

/-- Equality of the two quotient-valued adjacent-reflection shift classes determines the
dihedral extension.  The proof extracts two norm witnesses, simultaneously adjusts the target
lifts, and applies `twoReflectionExtensionIsoExact`. -/
noncomputable def twoReflectionExtensionIsoOfShiftClasses
    (G H : PlaneGroup)
    (dG : DihedralGenerators G) (dH : DihedralGenerators H)
    (cG : TwoReflectionExtensionData G dG) (cH : TwoReflectionExtensionData H dH)
    (eT : translationVectors G.carrier ≃+ translationVectors H.carrier)
    (horder : dG.order.toNat = dH.order.toNat)
    (hrotation : ∀ t : translationVectors G.carrier,
      eT (pointAction G.carrier dG.rotation.1 t) =
        pointAction H.carrier dH.rotation.1 (eT t))
    (hreflection : ∀ t : translationVectors G.carrier,
      eT (pointAction G.carrier dG.reflection t) =
        pointAction H.carrier dH.reflection (eT t))
    (hfirstClass :
      shiftClassEquivOfIntertwining eT dG.reflection dH.reflection hreflection
          2 dG.reflection_sq dH.reflection_sq cG.firstShiftClass =
        cH.firstShiftClass)
    (hsecondClass :
      shiftClassEquivOfIntertwining eT dG.secondReflection dH.secondReflection
          (secondReflectionAction_natural dG dH eT hrotation hreflection)
          2 dG.secondReflection_sq dH.secondReflection_sq cG.secondShiftClass =
        cH.secondShiftClass) :
    TranslationPreservingIso G H := by
  have hfirstRepresentatives :
      QuotientAddGroup.mk' (normTranslationSubgroup H dH.reflection 2 dH.reflection_sq)
          (fixedTranslationEquivOfIntertwining eT dG.reflection dH.reflection hreflection
            (liftPowerFixedTranslation G dG.reflection 2 dG.reflection_sq
              cG.firstLift cG.first_projection)) =
        QuotientAddGroup.mk' (normTranslationSubgroup H dH.reflection 2 dH.reflection_sq)
          (liftPowerFixedTranslation H dH.reflection 2 dH.reflection_sq
            cH.firstLift cH.first_projection) := by
    have htransported := hfirstClass
    change shiftClassEquivOfIntertwining eT dG.reflection dH.reflection hreflection
          2 dG.reflection_sq dH.reflection_sq
          (QuotientAddGroup.mk'
            (normTranslationSubgroup G dG.reflection 2 dG.reflection_sq)
            (liftPowerFixedTranslation G dG.reflection 2 dG.reflection_sq
              cG.firstLift cG.first_projection)) =
        QuotientAddGroup.mk'
          (normTranslationSubgroup H dH.reflection 2 dH.reflection_sq)
          (liftPowerFixedTranslation H dH.reflection 2 dH.reflection_sq
            cH.firstLift cH.first_projection) at htransported
    rw [shiftClassEquivOfIntertwining_mk] at htransported
    exact htransported
  have hfirstExists :=
    (shiftClass_mk_eq_mk_iff_exists_norm_add H dH.reflection 2
      dH.reflection_sq _ _).mp hfirstRepresentatives
  let u : translationVectors H.carrier := Classical.choose hfirstExists
  have hu := Classical.choose_spec hfirstExists
  have hu' := congrArg Subtype.val hu
  change eT cG.firstSquareShift =
    finiteNormHom H dH.reflection 2 u + cH.firstSquareShift at hu'
  let hsecondAction :=
    secondReflectionAction_natural dG dH eT hrotation hreflection
  have hsecondRepresentatives :
      QuotientAddGroup.mk'
          (normTranslationSubgroup H dH.secondReflection 2 dH.secondReflection_sq)
          (fixedTranslationEquivOfIntertwining eT dG.secondReflection
            dH.secondReflection hsecondAction
              (liftPowerFixedTranslation G dG.secondReflection 2
                dG.secondReflection_sq cG.secondLift cG.second_projection)) =
        QuotientAddGroup.mk'
          (normTranslationSubgroup H dH.secondReflection 2 dH.secondReflection_sq)
          (liftPowerFixedTranslation H dH.secondReflection 2
            dH.secondReflection_sq cH.secondLift cH.second_projection) := by
    have htransported := hsecondClass
    change shiftClassEquivOfIntertwining eT dG.secondReflection dH.secondReflection
          hsecondAction 2 dG.secondReflection_sq dH.secondReflection_sq
          (QuotientAddGroup.mk'
            (normTranslationSubgroup G dG.secondReflection 2 dG.secondReflection_sq)
            (liftPowerFixedTranslation G dG.secondReflection 2 dG.secondReflection_sq
              cG.secondLift cG.second_projection)) =
        QuotientAddGroup.mk'
          (normTranslationSubgroup H dH.secondReflection 2 dH.secondReflection_sq)
          (liftPowerFixedTranslation H dH.secondReflection 2 dH.secondReflection_sq
            cH.secondLift cH.second_projection) at htransported
    rw [shiftClassEquivOfIntertwining_mk] at htransported
    exact htransported
  have hsecondExists :=
    (shiftClass_mk_eq_mk_iff_exists_norm_add H dH.secondReflection 2
      dH.secondReflection_sq _ _).mp hsecondRepresentatives
  let v : translationVectors H.carrier := Classical.choose hsecondExists
  have hv := Classical.choose_spec hsecondExists
  have hv' := congrArg Subtype.val hv
  change eT cG.secondSquareShift =
    finiteNormHom H dH.secondReflection 2 v + cH.secondSquareShift at hv'
  apply twoReflectionExtensionIsoExact G H dG dH cG (cH.adjust u v) eT
    horder hrotation hreflection
  · exact hu'.trans (cH.firstSquareShift_adjust u v).symm
  · exact hv'.trans (cH.secondSquareShift_adjust u v).symm

end TwoReflectionExtensionData

end

end WallpaperGroups
