name: Deploy API documentation

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    name: Build and deploy documentation
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment:
      name: github-pages

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - name: Build with warnings treated as errors
        uses: leanprover/lean-action@38fbc41a8c28c4cbaec22d7f7de508ec2e7c0dd9 # v1.5.0
        with:
          build-args: "--wfail"

      - name: Generate and deploy API documentation
        uses: leanprover-community/docgen-action@10db47458f91456d87804787d3dfcd914b9a19e3 # main, 2026-07-26
        with:
          api-docs: true
          build-page: false
          deploy: true
          homepage: _site
          references: docs/references/schwarzenberger_17_plane_symmetry_groups.bib
